#!/bin/bash

cd ~/SAN/

python  main_Cora_node_classification.py --config 'configs/CORA/optimized'
#python  main_molpcba.py --config 'configs/MOLPCBA/optimized'
#python  main_molpcba.py --config 'configs/MOLPCBA/optimized'
#python  main_molpcba.py --config 'configs/MOLPCBA/optimized'



